FROM python:3.12-slim 

RUN apt-get update && apt-get install -y \
    gcc \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt 

COPY . .

ENV PYTHONPATH = /app 

CMD ["celery", "-A", "bot.tasks.generate_resume_task", "worker", "--loglevel=info", "--concurrency=4"]
